appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Gh0oS5cN2BClSJm+yKzMNkdqmKxL0UkkTPwNm39L9Yg/g13yGIUponPplJmfJdjkUcAQCRRuDnsTG+DxTJxFVm1wxOAGB14aNjVfmLB2Z9Nt7xBXdAwnIQPIa9x9+A26CDolGKm+OYsH4p7/Kwy88XrpQNIsQVQwNU7M9RDXozp7+eRjxW+uowinTrvgYhPzASAKHFV2NhVZr4P0FAcGrj3p9e6Yqbyl1CObFN+gedQ3GEMyGiI6NRNoWtbno40QvvEcmrP7OXrv9mmClaV5fruj7j6KAtpuORRyHJi3OAUikR6RIkBZvOYJuzc97D3u3zKzbDPD3x1hpHOtLczjh7pYYezWlpczK/qhSSP43cNqP7vZL5m92euplS22NNbEe10fo/y7aZ3FEG/n5qrQAnBHLo40PQgp0Cp7jgqyQKuzArIEAKB7AS14H/6UnOQONySMSfWF5WN4P9KHd74pA16+9bm8Sy+sPL2Uzfb1rOuJvvM7RBaV0P/7/ZkmByOWogyyKeSkdtchrO+afhYSHZ/7nm9b1iLB3JH3KoiyKYOQJWkJE1DhYQRK7zkyvCsNqlNmb5ZP05Oyf2yAiiJwzgZmYeXp2J5D1FkERh9TxeTz3eS5AY414h6NdmqZYZPBcwqgzQrZv70y3WfAhsUJ7Fc/F3r0CFAvRzxyyeuQbik=}
